function SideBar(props){

    return(
      <div className="container">
        <div className="row">
          <h3>Clouds</h3> // Clouds can change if need be
          <hr/>
            <p>Cloud typeA</p> // Each p will be generated by a function mapping over the different cloud type
            <p>Cloud typeB</p>
            <p>Cloud typeC</p>
        </div>
      <div className="row">
        <h3> Filters</h3>
      </div>
      <div className="row">
        <h5>Color</h5>
        <hr/>
          <div class="input-group">
            <div class="input-group-addon">
              <input type="checkbox" aria-label="...">
                <span>White</span>//A color
              </div>
            <div class="input-group-addon">
              <input type="checkbox" aria-label="...">
                <span>Grey</span>//B color
              </div>
              <div class="input-group-addon">
                <input type="checkbox" aria-label="...">
                  <span>Avocado</span>//C color
                </div>
          </div><!-- /input-group -->
      </div>
          <h5>Locations</h5>
          <hr/>
          <div class="input-group-addon">
            <input type="checkbox" aria-label="...">
              <span>Americas</span>//A Area
            </div>
          <div class="input-group-addon">
            <input type="checkbox" aria-label="...">
              <span> Eurasia</span>//B Area
            </div>
            <div class="input-group-addon">
              <input type="checkbox" aria-label="...">
                <span>Austroasia</span>//C Area
              </div>
          </div><!-- /input-group -->
      </div><!-- /.row -->
    </div>
  )
}
